-- =================================================================
-- customer-db (Microservicio de Clientes)
-- =================================================================

-- 1. Tabla de Clientes (que hereda de Persona)
CREATE TABLE IF NOT EXISTS customers (
    -- Campos de PersonEntity
    name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    identification VARCHAR(15) NOT NULL UNIQUE,
    address VARCHAR(200) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    
    -- Campos de CustomerEntity
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_customer_identification ON customers(identification);


-- =================================================================
-- account-db (Microservicio de Cuentas)
-- =================================================================

-- 1. Tabla de Cuentas
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(20) NOT NULL UNIQUE,
    account_type VARCHAR(20) NOT NULL,
    initial_balance NUMERIC(10, 2) NOT NULL,
    status BOOLEAN NOT NULL,
    customer_id BIGINT NOT NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_account_customer_id ON accounts(customer_id);

---

-- 2. Tabla de Movimientos
CREATE TABLE IF NOT EXISTS movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    movement_type VARCHAR(20) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    balance NUMERIC(10, 2) NOT NULL,
    account_id BIGINT NOT NULL,
    
    -- Llave foránea a la tabla de Cuentas
    CONSTRAINT fk_movement_account
        FOREIGN KEY(account_id) 
        REFERENCES accounts(id)
        ON DELETE CASCADE
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_movement_account_id ON movements(account_id);

---

-- 3. Tabla de Libro Contable (Ledger) - Para Auditoría y Reportes
CREATE TABLE IF NOT EXISTS ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    movement_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    entry_type VARCHAR(10) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    balance_before NUMERIC(10, 2) NOT NULL,
    balance_after NUMERIC(10, 2) NOT NULL,
    description VARCHAR(500),
    initiated_by VARCHAR(100)
);

-- Índices optimizados para reportes (como se definen en la entidad)
CREATE INDEX IF NOT EXISTS idx_ledger_account_timestamp ON ledger_entries(account_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_ledger_movement ON ledger_entries(movement_id);