package com.bank.account.application.output.port;

import com.bank.account.domain.model.LedgerEntry;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Output port for ledger entry persistence operations.
 * This follows the Hexagonal Architecture pattern, defining the contract
 * for ledger entry storage without depending on a specific implementation.
 * Implementation note: All operations are reactive (return Mono/Flux) even though
 * the underlying JPA is blocking. The adapter will handle the reactive wrapping.
 */
public interface LedgerRepositoryPort {

    /**
     * Saves a new ledger entry.
     * This is an append-only operation - entries are never updated or deleted.
     *
     * @param ledgerEntry The ledger entry to save
     * @return A Mono that emits the saved ledger entry with its generated ID
     */
    Mono<LedgerEntry> saveLedgerEntry(LedgerEntry ledgerEntry);

    /**
     * Finds all ledger entries for a specific account, ordered chronologically.
     *
     * @param accountId The account ID
     * @return A Flux that emits all ledger entries for the account
     */
    Flux<LedgerEntry> findByAccountId(Long accountId);

    /**
     * Finds ledger entries for an account within a specific date range.
     * Used for generating periodic statements.
     *
     * @param accountId The account ID
     * @param startDate Start of the period
     * @param endDate End of the period
     * @return A Flux that emits ledger entries within the date range
     */
    Flux<LedgerEntry> findByAccountIdAndDateRange(Long accountId, LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Finds ledger entries for multiple accounts within a date range.
     * Used for consolidated reports across multiple accounts.
     *
     * @param accountIds List of account IDs
     * @param startDate Start of the period
     * @param endDate End of the period
     * @return A Flux that emits ledger entries for all specified accounts
     */
    Flux<LedgerEntry> findByAccountIdsAndDateRange(List<Long> accountIds, LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Finds all ledger entries generated by a specific movement.
     * Typically, each movement generates one ledger entry.
     *
     * @param movementId The movement ID
     * @return A Flux that emits ledger entries for the movement
     */
    Flux<LedgerEntry> findByMovementId(Long movementId);

    /**
     * Counts the total number of ledger entries for an account.
     * Useful for pagination and statistics.
     *
     * @param accountId The account ID
     * @return A Mono that emits the count of entries
     */
    Mono<Long> countByAccountId(Long accountId);
}