package com.bank.account.infrastructure.output.adapter.jpa.repository;

import com.bank.account.infrastructure.output.adapter.jpa.entity.LedgerEntryEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Spring Data JPA Repository for LedgerEntry.
 *
 * Note: This is an append-only repository.
 * There are NO update or delete methods by design (audit trail integrity).
 */
public interface LedgerSpringRepository extends JpaRepository<LedgerEntryEntity, Long> {

    /**
     * Find all ledger entries for a specific account, ordered by timestamp.
     * Useful for generating account statements and audit reports.
     *
     * @param accountId The account ID
     * @return List of ledger entries ordered by timestamp (oldest first)
     */
    List<LedgerEntryEntity> findByAccountIdOrderByTimestampAsc(Long accountId);

    /**
     * Find ledger entries for an account within a date range.
     * Used for generating periodic reports and statements.
     *
     * @param accountId The account ID
     * @param startDate Start of the period
     * @param endDate End of the period
     * @return List of ledger entries in the specified period
     */
    @Query("SELECT l FROM LedgerEntryEntity l WHERE l.accountId = :accountId " +
            "AND l.timestamp BETWEEN :startDate AND :endDate " +
            "ORDER BY l.timestamp ASC")
    List<LedgerEntryEntity> findByAccountIdAndTimestampBetween(
            @Param("accountId") Long accountId,
            @Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate
    );

    /**
     * Find all ledger entries for multiple accounts within a date range.
     * Used for generating reports across multiple accounts.
     *
     * @param accountIds List of account IDs
     * @param startDate Start of the period
     * @param endDate End of the period
     * @return List of ledger entries
     */
    @Query("SELECT l FROM LedgerEntryEntity l WHERE l.accountId IN :accountIds " +
            "AND l.timestamp BETWEEN :startDate AND :endDate " +
            "ORDER BY l.accountId, l.timestamp ASC")
    List<LedgerEntryEntity> findByAccountIdsAndTimestampBetween(
            @Param("accountIds") List<Long> accountIds,
            @Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate
    );

    /**
     * Find ledger entries by movement ID.
     * Used to trace all ledger entries generated by a specific movement.
     *
     * @param movementId The movement ID
     * @return List of ledger entries for this movement
     */
    List<LedgerEntryEntity> findByMovementId(Long movementId);

    /**
     * Count entries for an account (useful for pagination and statistics).
     *
     * @param accountId The account ID
     * @return Total number of entries
     */
    Long countByAccountId(Long accountId);
}